version: "2"
services:
 web:
  container_name: contratos-interface
  image: teste/contratos-interface
  ports:
    - "16000:16001"
  depends_on:
    - mongo
    - db
  links:
    - mongo
    - db
  db:
    container_name: contratos-api
    image: teste/contratos-api
  
  services:
    mongo:
    container_name: contratos
    image: contratos
    ports:
      - "27017:27017"
